# Generated by Django 2.2 on 2021-03-25 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dialogmemebers',
            options={'ordering': ['dialog', '-role', 'member'], 'verbose_name': 'люди в диалоге', 'verbose_name_plural': 'люди в диалогах'},
        ),
    ]
